/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */
import type { ApiArticlesGetCollection200SearchMappingItem } from './apiArticlesGetCollection200SearchMappingItem';

export type ApiArticlesGetCollection200Search = {
  '@type'?: string;
  template?: string;
  variableRepresentation?: string;
  mapping?: ApiArticlesGetCollection200SearchMappingItem[];
};
