/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */
import type { ApiArticlesGetCollection200SearchMappingItemProperty } from './apiArticlesGetCollection200SearchMappingItemProperty';

export type ApiArticlesGetCollection200SearchMappingItem = {
  '@type'?: string;
  variable?: string;
  property?: ApiArticlesGetCollection200SearchMappingItemProperty;
  required?: boolean;
};
