/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */

export type ApiArticlesGetCollection200View = {
  '@id'?: string;
  '@type'?: string;
  first?: string;
  last?: string;
  previous?: string;
  next?: string;
};
