/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */
import type { ArticleJsonld } from './articleJsonld';
import type { ApiArticlesGetCollection200View } from './apiArticlesGetCollection200View';
import type { ApiArticlesGetCollection200Search } from './apiArticlesGetCollection200Search';

export type ApiArticlesGetCollection200 = {
  member: ArticleJsonld[];
  /** @minimum 0 */
  totalItems?: number;
  view?: ApiArticlesGetCollection200View;
  search?: ApiArticlesGetCollection200Search;
};
