/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */
import type { ArticleJsonldContextOneOfHydra } from './articleJsonldContextOneOfHydra';

export type ArticleJsonldContextOneOf = {
  '@vocab': string;
  hydra: ArticleJsonldContextOneOfHydra;
  [key: string]: unknown;
 };
