/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */
import type { ArticleJsonldContext } from './articleJsonldContext';

export interface ArticleJsonld {
  readonly '@context'?: ArticleJsonldContext;
  readonly '@id'?: string;
  readonly '@type'?: string;
  readonly id?: number;
  title?: string;
  description?: string;
}
