/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */
import type { ArticleJsonldContextOneOf } from './articleJsonldContextOneOf';

export type ArticleJsonldContext = string | ArticleJsonldContextOneOf;
