/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */

export type ArticleJsonldContextOneOfHydra = typeof ArticleJsonldContextOneOfHydra[keyof typeof ArticleJsonldContextOneOfHydra];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ArticleJsonldContextOneOfHydra = {
  'http://wwww3org/ns/hydra/core#': 'http://www.w3.org/ns/hydra/core#',
} as const;
