/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */

export interface Article {
  readonly id?: number;
  title?: string;
  description?: string;
}
